import time


print("                SLIME           ")
print("")
print("")
print("")
print("")
print("게임을 시작 하시려면 s를 눌러주세요.")
a = input("")
if a == "s":
    print("게임을 시작합니다.")
    print ("로딩 중")
    time.sleep(3)
    print("어느 곳에서 당신은 갇혀 있습니다.")
    time.sleep(3)
    print("당신은 이 유리 쳐보고 알아냈습니다.")
    time.sleep(3)
    print("톡 치면 깨질정도로 약하는 것을 알아냈습니다.")
    time.sleep(3)
    print("당신은 어떻게 하실건가요?")
    print('1. 유리를 부신다.')
    print('2. 유리를 부수지 않는다.')
    a = input("")
    
    if a == "2":
        print("엔딩 1, (유리 안에서 사망)")
        time.sleep(3)
        print("게임을 종료합니다.")
    else:
        print("유리를 부셨습니다.")
        time.sleep(3)
        print("당신이 나와보니 거기는 실험실이었습니다.")
        time.sleep(3)
        print("그리고 사이렌이 울리고 있었습니다.")
        time.sleep(3)
        print("당신은 이곳에서 탈출해야 합니다.")
        print('1. 왼쪽으로 간다.')
        print('2. 오른쪽으로 간다.')
        a = input("")
        if a == "1":
            print("왼쪽으로 갔습니다.")
            time.sleep(3)
            print("왼쪽으로 간 당신.")
            time.sleep(3)
            print("총기로 무장한 경비가 이쪽으로 달려옵니다.")
            time.sleep(3)
            print("당신은 어떻게 하시겠습니까?")
            print("1. 숨는다.")
            print("2. 맞서 싸운다.")
            a = input("")
            if a == "2":
                print("당신은 맞서 싸웠습니다.")
                time.sleep(3)
                print("총에 한발 맞자 당신은 깨달았습니다.")
                time.sleep(3)
                print("당신의 몸은 허약하다는 것을.")
                time.sleep(3)
                print("당신은 쓰러졌습니다.")
                time.sleep(3)
                print("엔딩 2(총에 맞아 사망)")
                time.sleep(3)
                print("게임을 종료합니다.")
            else:
                print("당신은 숨었습니다.")
                time.sleep(3)
                print("숨은 당신 어떻게 하시겠습니까?")

                print("1. 경비를 기습한다.")
                print("2. 숨어서 기다린다.")
                a = input("")
                if a == "2":
                    print("당신은 숨어서 기다렸습니다.")
                    time.sleep(3)
                    print("그러자 경비는 그냥 지나갔습니다.")
                    time.sleep(3)
                    print("경비가 지나가자 당신은 마저 갔습니다")
                else:
                    print("당신은 경비를 기습했습니다.")
                    time.sleep(3)
                    print("당신은 경비를 사살했습니다.")
                    time.sleep(3)
                    print("그렇지만 당신도 치명상을 입었습니다.")
                    time.sleep(3)
                    print("당신은 앉아 있다가 경비를 손으로 만졌습니다.")
                    time.sleep(3)
                    print("그러더니 경비의 모습으로 변했습니다.")
                    time.sleep(3)
                    print("아픈 상처도 모두 치료 되었습니다.")
                    time.sleep(3)
                    print("당신은 깨달았습니다.")
                    time.sleep(3)
                    print("자신에게 흡수 능력이 있다는 것을 알았습니다.")
                    time.sleep(3)
                    print("그러고 곧 사이렌이 끝났습니다.")
                    time.sleep(3)
                    print("그러자 당신은 경비원의 기억이 떠올랐습니다.")
                    time.sleep(3)
                    print("당신은 경비원의 기억을 바탕으로 행동하기로 결심했습니다.")
                    time.sleep(3)
                    print("당신은 경비의 옷을 갈아입고 휴게실로 갔습니다.")
                    time.sleep(3)
                    print("그러자 경비 책임자는 연설을 하고 퇴근을 하라고 했습니다.")
                    time.sleep(3)
                    print("1. 남아서 기다리다가 사람들을 급습한다.")
                    print("2. 옷을 갈아입고 퇴근한다.")
                    a = input("")
                    if a == "1":
                        print("당신은 남아서 일을 더하다 가겠다고 경비 책임자에게 말씀을 하고 휴게실로 돌아갔습니다.")
                        time.sleep(3)
                        print("그곳에서 당신은 경비의 일과를 관찰하며 정보를 수집했습니다.")
                        time.sleep(3)
                        print("제일 만만한 사람을 골라서 급습했습니다.")
                        time.sleep(3)
                        print ("그렇지만 거기는 하필 cctv가 있었습니다.")
                        time.sleep(3)
                        print("그리고 그 cctv는 관리 책임자가 보고 있었습니다.")
                        time.sleep(3)
                        print ("당신은 관리 책임자에게 잡혔습니다.")
                        time.sleep(3)
                        print("그러고 당신은 다시 감금 되었습니다.")
                        time.sleep(3)
                        print("엔딩 3(다시 감금)")
                        time.sleep(3)
                        print("게임을 종료합니다.")
                    else:
                        print("당신은 옷을 갈아입고 퇴근을 했습니다.")

            a = input("")
            if a == "2":
                print("오른쪽으로 간 당신.")
                time.sleep(3)
                print("아주 많은 기계가 보입니다.")
                time.sleep(3)
                print("당신은 이 기계들을 어떻게 하시겠습니까?")
                print("1. 기계를 파괴한다.")
                print("2. 기계를 무시하고 간다.")
                print("3. 기계들을 조작한다.")
            a = input("")
            if a == "1":
                print("당신은 기계를 파괴했습니다.")
                time.sleep(3)
                print("그 기계는 엄청나게 큰소리를 내기 시작했습니다.")
                time.sleep(3)
                print("그러더니 그 기계는 아주 큰 소리를 내더니 폭발했습니다.")
                time.sleep(3)
                print("당신은 쓰러졌습니다.")
                time.sleep(3)
                print("엔딩 4(기계 폭발로 사망)")
                time.sleep(3)
                print("게임을 종료합니다.")
            elif a == "2":
                print ("가다 보니 비상문 탈출구가 보였습니다")
                time.sleep(3)
                print("당신은 그곳으로 갔습니다.")
                time.sleep(3)
                print("그리고 그 문을 열으니 아주 밝은 햇살이 비췄습니다.")
            else:
                print("그 기계를 조작하니 이상한 관이 나왔습니다.")
                time.sleep(3)
                print("그 관은 유리로 되어있고 안에는 이상한 액체가 들어있었습니다.")
                time.sleep(3)
                print("그 유리관을 깨고 그 액체를 만지니 당신의 몸이 이상해졌습니다.")
                time.sleep(3)
                print("그러더니 당신은 기절 했습니다.")
                time.sleep(3)
                print("        10분후        ")
                
                time.sleep(3)
                print("당신은 깨어났습니다.")
                time.sleep(3)
                print("놀란 마음에 당신은 당신의 몸을 만져 보았습니다.")
                time.sleep(3)
                print("어쩨서인지 당신의 몸은 아주 단단해 졌습니다")
                time.sleep(3)
                print("이제 총알 조차도 막을수 있을것처럼 느껴 졌습니다")
                time.sleep(3)
                print("저기 멀리서 경비원이 다가 오는것을 보았습니다.")
                time.sleep(3)
                print("그러나 당신은 움직일세도 없이 총에 맞았습니다.")
                time.sleep(3)
                print("퍽,퍼버버벅,퍼버벅")
                time.sleep(3)
                print("그러나 당신은 죽지 않았습니다.")
                time.sleep(3)
                print("약간 살살 아플뿐 몸에는 아무 이상이 없었습니다.")
                time.sleep(3)
                print("당신은 경비원을 쳐다 보았습니다.")
                time.sleep(3)
                print("그러자 경비원은 당신을 보고 놀라서 더욱 총을 쏘았습니다.")
                time.sleep(3)
                print("당신은 그 총알을 막았습니다.")
                time.sleep(3)
                print("그리고 그 경비원에게 달려들었습니다.")
                time.sleep(3)  
                print("경비원은 당신을 보고 놀라서 도망치려고 했습니다.")
                time.sleep(3)
                print("그러나 당신은 그 경비원을 잡았습니다.")
                time.sleep(3)
                print("그리고 경비원을 쓰러뜨렸습니다.")
                time.sleep(3)
                print("당신은 경비원의 옷으로 갈아 입으려고 손을 댔습니다.")
                time.sleep(3)
                print("그러더니 경비의 모습으로 변했습니다.")
                time.sleep(3)
                print("당신은 경비의 모습으로 변한 당신을 보고 놀랐습니다.")
                time.sleep(3)
                print("그러자 당신은 경비원의 기억이 떠올랐습니다.")
                time.sleep(3)
                print("당신은 경비원의 기억을 바탕으로 행동하기로 결심했습니다.")
                time.sleep(3)
                print("당신은 경비의 옷을 갈아입고 휴게실로 갔습니다.")
                time.sleep(3)
                print("그러자 경비 책임자는 연설을 하고 퇴근을 하라고 했습니다.")
                time.sleep(3)
                print("1. 남아서 기다리다가 사람들을 급습한다.")
                print("2. 옷을 갈아입고 퇴근한다.")
                a = input("")
                if a == "1":
                    print("당신은 남아서 일을 더하다 가겠다고 경비 책임자에게 말씀을 하고 휴게실로 돌아갔습니다.")
                    time.sleep(3)
                    print("그곳에서 당신은 경비의 일과를 관찰하며 정보를 수집했습니다.")
                    time.sleep(3)
                    print("제일 만만한 사람을 골라서 급습했습니다.")
                    time.sleep(3)
                    print ("그렇지만 거기는 하필 cctv가 있었습니다.")
                    time.sleep(3)
                    print("그리고 그 cctv는 관리 책임자가 보고 있었습니다.")
                    time.sleep(3)
                    print ("당신은 관리 책임자에게 잡혔습니다.")
                    time.sleep(3)
                    print("그러고 당신은 다시 감금 되었습니다.")
                    time.sleep(3)
                    print("엔딩 3(다시 감금)")
                    time.sleep(3)
                    print("게임을 종료합니다.")
                else:
                    print("당신은 옷을 갈아입고 퇴근을 했습니다.")
