import time


print("                SLIME           ")
print("")
print("")
print("")
print("")
print("게임을 시작 하시려면 s를 눌러주세요.")
a = input("")
if a == "s":
    print("게임을 시작합니다.")
    print ("로딩중")
    time.sleep(5)
    print("어느 곳에서 당신은 갇혀 있습니다.")
    time.sleep(3)
    print("당신은 이 유리 쳐 보고 알아냈습니다.")
    time.sleep(3)
    print("톡 치면 깨질정도로 약하는것을 알아냈습니다.")
    time.sleep(3)
    print("당신은 어떻게 하실껀가요?")
    time.sleep(3)
    print('1. 유리를 부신다.')
    print('2. 유리를 부수지 않는다.')
    a = input("")
    if a == "1":
        print("유리를 부셨습니다.")
        time.sleep(3)
        print("당신이 나와보니 거기는 실험실이었습니다.")
        time.sleep(3)
        print("그리고 사이렌이 울리고 있었습니다.")
        time.sleep(3)
        print("당신은 이곳에서 탈출해야 합니다.")
        time.sleep(3)
        print("길은 총 2가지 입니다.")
        print('1. 왼쪽으로 간다.')
        print('2. 오른쪽으로 간다.')
        a = input("")
        if a == "1":
            print("왼쪽으로 갔습니다.")
            time.sleep(3)
            print("왼쪽으로 간 당신.")
            time.sleep(3)
            print("총기로 무장한 경비가 이쪽으로 달려옵니다.")
            time.sleep(3)
            print("당신은 어떻게 하시겠습니까?")
            print("1. 숨는다.")
            print("2. 맞서 싸운다.")
            a = input("")
            if a == "1":
                print("당신은 숨었습니다.")
                time.sleep(3)
                print("숨은 당신 어떻게 하시겠습니까?")
                time.sleep(3)
                print("1. 경비를 기습한다.")
                print("2. 숨어서 기다린다.")
                a = input("")
                if a == "1":
                    print("당신은 경비를 기습했습니다.")
                    time.sleep(3)
                    print("당신은 경비를 사살했습니다.")
                    time.sleep(3)
                    print("그렇지만 당신도 치명상을 입었습니다.")
                    time.sleep(3)
                    print("당신은 앉아 있다가 경비를 손으로 만졌습니다.")
                    time.sleep(3)
                    print("그러더니 경비의 모습으로 변했습니다.")
                    time.sleep(3)
                    print("아픈 상처도 모두 치료 되었습니다.")
                    time.sleep(3)
                    print("당신은 깨달았습니다.")
                    time.sleep(3)
                    print("자신에게 흡수 능력이 있다는 것을 알았습니다.")
                    time.sleep(3)
                    print("그러고 곧 사이렌이 끝났습니다.")
                    time.sleep(3)
                    print("그러자 모든 경비는 경비 책임장이 불러서 연설을 하고 퇴근을 하라고 했습니다.")
                    time.sleep(3)
                    print("1. 남아서 기다리다가 사람들을 급습한다.")
                    print("2. 옷을 갈아입고 퇴근한다.")
                    a = input("")
                    if a == "1":
                        print("당신은 남아서 일을 더하다 가겠다고 경비 책임자에게 말씀을 하고 휴게실로 돌아갔습니다.")
                        time.sleep(3)
                        print("그곳에서 당신은 경비의 일과를 관찰하며 정보를 수집했습니다.")
                        time.sleep(3)
                        print("제일 만만한 사람을 골라서 급습했습니다.")
                        time.sleep(3)
                        print ("그렇지만 거기는 하필 cctv가 있었습니다.")
                        time.sleep(3)
                        print("그리고 그 cctv는 관리 책임자가 보고 있었습니다.")
                        time.sleep(3)
                        print ("당신은 관리 책임자에게 잡혔습니다.")
                        time.sleep(3)
                        print("그러고 당신은 다시 감금 되었습니다.")
                        time.sleep(3)
                        print("엔딩 3(다시 감금)")
                        time.sleep(3)
                        print("게임을 종료합니다.")

                    else:
                        print("당신은 옷을 갈아입고 퇴근을 했습니다.")
                else:
                    print("당신은 숨어서 기다렸습니다.")
            else:
                print("당신은 맞서 싸웠습니다.")
                time.sleep(3)
                print("총에 한발 맞자 당신은 깨달았습니다.")
                time.sleep(3)
                print("당신의 몸은 허약하다는 것을.")
                time.sleep(3)
                print("당신은 쓰러졌습니다.")
                time.sleep(3)
                print("엔딩 2(총에 맞아 사망)")
                time.sleep(3)
                print("게임을 종료합니다.")
        else:
            print("오른쪽으로 갔습니다.")
    else:
        print("엔딩 1, (유리 안에서 사망)")
        time.sleep(3)
        print("게임을 종료합니다.")
else:
    print("잘못된 입력입니다.")
